// Title: PowerShell Dynamic Module Invocation Via ExportedCommands Array Index
// Author: Norbert Jaśniewicz (AlphaSOC), Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2026-10-06
// Level: high
// Description: Detects PowerShell processes invoked with obfuscated command lines that enumerate Microsoft.PowerShell.Utility
// exported commands and invoke cmdlets indirectly by array index. This technique is used to evade
// detections that look for explicit strings such as Invoke-RestMethod or Invoke-Expression.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.stealth, attack.t1027.010, attack.t1059.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_cmdlet_invocation_via_exported_commands_array_index.yml
// False Positives:
//   - Legitimate use of exported commands array indexing during PowerShell command execution (should be rare)

DeviceProcessEvents
| where ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") or (ProcessVersionInfoOriginalFileName in~ ("powershell.exe", "pwsh.dll"))) and ProcessCommandLine =~ "*[*]*" and ((ProcessCommandLine contains "Get-Module " or ProcessCommandLine contains "gmo ") and (ProcessCommandLine contains "ListAvailable" and ProcessCommandLine contains "Microsoft.PowerShell.Utility" and ProcessCommandLine contains "ExportedCommands" and ProcessCommandLine contains "Values"))